### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jrodl3r** [jrodl3r/ng-fire-universal#1]
# Roadmap
**_Objective:_** Achieve v1.0.0 high-score status and launch proper 🚀 

---

- [ ] Progressive Web App (NGSW)
- [x] Server-Side Rendering
- [ ] SEO / Metatag Service
- [ ] Home, Get Started Pages + Docs
- [ ] Public + Private Projects
- [ ] Project Photos
- [ ] Social Cards + Sharing w/ Metadata

---

- [ ] Add `Created` Field + Logic to User Schema
- [ ] Move DB Rules into repo + Update Docs
- [ ] Unit Tests + Continuous Integration (Travis-Ci)
- [ ] Stripe Payments & Subscriptions (Feature Branch)
- [ ] **Tag & Release v1.0.0** 🔥

---

**_Ready:_**

🕘Progressive Web App - Lighthouse Score:  💯
⇢ Server-Side Rendering w/ Angular Universal
⇢ User Media Management w/ Firebase Cloud Storage
⇢ Role-Based Admin Access Panel
⇢ User Preferences (Profile, Account & Dashboard)
⇢ Core Strategies & Concepts (Lazy-Loading, Child-Routing, Auth Guard, etc.)
⇢ Core Services Modules [Auth, SEO, Forms, Projects, Settings + More]
⇢ Firebase User Authorization [email/password + oAuth]
⇢ Bootstrap + MDB + jQuery
